rsvp:
  use_code: false
  code: 1234
  code_md5: 81dc9bdb52d04dc20036dbd8313ed055
  post_address: https://script.google.com/macros/s/AKfycbyPrWqSgI5GtAdPmv7_s5BqgFKZs4grEv0WiVrh-yUlEC4Z8fk/exec
  code_location: You can put the code on the back of your RSVP card, or turn off this functionality all together. The code for this sample is 1234
  yes_text: I'll be there
  no_text: I can't make it
  no_extra_guests_message: As much as we would love to have everyone, please only include guests that were listed on your invitation
  submit_text: RSVP
  cancel_text: Cancel
  song_text: What songs will get you dancing?

people:
  families_header: Our Families 
  families_text: We would be nothing if it wasn't for the love and support of our wonderful parents and siblings.
  kids_header: Little Ones
  kids_text: We’re so lucky to have our sweet puppies help us celebrate the big day.
  wedding_party_header: Wedding Party
  